-- Run this inside your Supabase project's SQL Editor to set up the AuraHQ DB

CREATE TABLE users (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(50) NOT NULL -- 'manager', 'engineer', 'client'
);

CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  deadline DATE NOT NULL,
  tech_stack TEXT NOT NULL, 
  completed_stack TEXT,
  budget_allocated NUMERIC NOT NULL,
  budget_spent NUMERIC DEFAULT 0,
  status VARCHAR(50) DEFAULT 'In Progress',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE project_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  event_type VARCHAR(50) NOT NULL, -- 'client_side', 'engineering_side'
  description TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Mock Data
INSERT INTO users (id, name, role) VALUES 
('MGR-01', 'Alice (Manager)', 'manager'),
('ENG-01', 'Bob (Engineer)', 'engineer');
